// ヒトヤク — 薬剤師データ + カテゴリ・タグ定義

const SPECIALTIES = [
  { id: 'kampo',      label: '漢方',         hue: 140 },
  { id: 'otc',        label: '市販薬',       hue:  30 },
  { id: 'supplement', label: 'サプリメント',  hue:  50 },
  { id: 'women',      label: '女性の健康',    hue: 340 },
  { id: 'pediatric',  label: '子育て・小児',  hue:  20 },
  { id: 'lifestyle',  label: '生活習慣',      hue: 200 },
  { id: 'chronic',    label: '慢性疾患',      hue: 220 },
  { id: 'interact',   label: '飲み合わせ',    hue: 280 },
  { id: 'sideeffect', label: '副作用',        hue:   0 },
  { id: 'language',   label: '外国語対応',    hue: 180 },
];

const PHARMACISTS = [
  {
    id: 'p01',
    name: '井出 奈央',
    nameKana: 'いで なお',
    title: '薬剤師 / 管理薬剤師',
    pharmacyName: 'よしな薬局 野江本店',
    location: '大阪府・城東区',
    photo: 'photos/p01.jpg',
    photoSeed: 'nao',
    photoHue: 140,
    specialties: ['interact', 'sideeffect', 'otc', 'supplement', 'lifestyle'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '薬を減らしたいと思ったら、まずは"いま困っていること"と"本当はどうなりたいか"を一緒に整理してみませんか。',
    profile: '外資系製薬メーカーのMRとして医療機関を担当後、調剤薬局へ転身。派遣薬剤師として10店舗以上で多くの患者さんと向き合いながら、司会業・講師業で培った「伝える力」も磨きました。2024年に「もっと患者さんにメリットを感じてもらえる薬局を作りたい」という想いで独立し、よしな薬局 野江本店を開局。「背景まで聴く、寄り添い相談」を大切にしています。',
    career: [
      '外資系製薬メーカーにてMRとして開業医・病院を担当',
      '調剤薬局へ転身、派遣薬剤師として10店舗以上で経験を積む',
      '司会業・講師業を並行しながら「伝える力」を磨く',
      '2024年 よしな薬局 野江本店を開局・管理薬剤師として運営',
    ],
    consultationStyle: '困りごとの背景と"本当はどうなりたいか"を確認し、できること・今は難しいことを分けて、無理のない選択肢を一緒に探します。',
    availableMethods: ['LINE', 'オンライン面談', '店舗相談', 'メール'],
    tags: ['飲み合わせ', '市販薬', '副作用', 'サプリ', '減薬相談', '生活習慣'],
    yearsOfExperience: 15,
  },
  {
    id: 'p02',
    name: '二村 将豪',
    nameKana: 'ふたむら まさとし',
    title: '薬剤師 / 新生ファーマシー代表',
    pharmacyName: '新生ファーマシー',
    location: '愛知県・名古屋市',
    photo: 'photos/p02.jpg',
    photoSeed: 'masatoshi',
    photoHue: 200,
    specialties: ['otc', 'interact', 'sideeffect', 'lifestyle'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '「こんなこと聞いていいのかな」そんな声に、薬剤師として安心を届けたいと思っています。',
    profile: '大手ドラッグストアでの勤務を経て薬剤師として5年以上のキャリアを積み、現在は愛知県内で複数の薬局を運営しながら自らも現場に立っています。OTC医薬品（市販薬）から調剤まで幅広く対応。処方薬と市販薬の飲み合わせ、市販薬の正しい選び方など、気軽に聞けなかった相談をていねいにサポートします。',
    career: [
      '大手ドラッグストアにてOTC・調剤を担当',
      '薬剤師として5年以上のキャリアを積む',
      '株式会社将薬 新生ファーマシーを設立・代表として複数の薬局を運営',
    ],
    consultationStyle: '丁寧な聞き方と安心できる雰囲気づくりを大切に。「正しく伝えること」より「相手を正しく理解すること」を優先します。',
    availableMethods: ['LINE', 'オンライン面談', '店舗相談'],
    tags: ['市販薬', '飲み合わせ', 'OTC', '副作用', '生活習慣'],
    yearsOfExperience: 6,
  },
  {
    id: 'p03',
    name: '石田 朋之',
    nameKana: 'いしだ ともゆき',
    title: '薬剤師 / 漢方相談歴7年以上',
    pharmacyName: '草漢堂グループ',
    location: '愛知県',
    photo: 'photos/p03.jpg',
    photoSeed: 'tomoyuki',
    photoHue: 120,
    specialties: ['kampo', 'women', 'chronic'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '「漢方か、病院か」ではなく、両方を組み合わせてあなたに合った最適な方法を一緒に探します。',
    profile: '大手調剤薬局の薬局長を経て、「薬で症状を抑えるだけでは本当の治療にならない」という問いから漢方の世界へ。漢方を処方するクリニック前薬局での勤務経験を経て、草漢堂グループにて漢方相談7年以上。不妊・月経不順・不眠・慢性的な皮膚トラブルなど、病院では解決できなかった不調に向き合っています。',
    career: [
      '大手調剤薬局にて薬局長として西洋医療に従事',
      '漢方を処方するクリニック前薬局へ転身',
      '草漢堂グループへ参画、漢方相談歴7年以上',
    ],
    consultationStyle: 'わからないことに正直であること、患者さんと一緒に向き合い続ける「並走型」のスタイルを大切にしています。',
    availableMethods: ['オンライン面談', '店舗相談'],
    tags: ['漢方', '女性の健康', '不妊', '不眠', '皮膚トラブル', '慢性疾患'],
    yearsOfExperience: 10,
  },
  {
    id: 'p04',
    name: '中村 幸子',
    nameKana: 'なかむら ゆきこ',
    title: '薬剤師 / 漢方相談歴30年以上',
    pharmacyName: '草漢堂グループ｜漢方明昭堂',
    location: '愛知県・名古屋市昭和区',
    photo: 'photos/p04.jpg',
    photoSeed: 'yukiko',
    photoHue: 340,
    specialties: ['kampo', 'women', 'lifestyle'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '女性の一生に寄り添う漢方相談。30年以上の経験で、あなたの体に合った答えを一緒に探します。',
    profile: '実家の薬局を手伝ったことをきっかけに漢方の道へ。大阪の病院での勤務で西洋医療も経験後、実家の薬局を継承。さらに上海中医薬大学附属日本校で本格的に学び直しました。現在は草漢堂グループの一員として活動。不妊・更年期・生理不順・PMS・冷えなど女性特有のお悩みを中心に、食養生・生活養生を取り入れた根本的なアプローチで30年以上支えてきました。',
    career: [
      '実家薬局での勤務をきっかけに漢方へ',
      '大阪の病院にて西洋医療の現場を経験',
      '実家薬局を継承',
      '上海中医薬大学附属日本校にて漢方を本格的に学ぶ',
      '草漢堂グループ｜漢方明昭堂にて相談業務（漢方歴30年以上）',
    ],
    consultationStyle: '食養生・生活養生を取り入れながら、一人ひとりの体質に寄り添ったオーダーメイドの相談を心がけています。',
    availableMethods: ['LINE', 'オンライン面談', '店舗相談'],
    tags: ['漢方', '女性の健康', '更年期', '不妊', 'PMS', '30年以上の実績'],
    yearsOfExperience: 30,
  },
  {
    id: 'p05',
    name: '角 裕也',
    nameKana: 'すみ ゆうや',
    title: '薬剤師 / 草漢堂薬局 ほのぼの調剤',
    pharmacyName: '草漢堂薬局 ほのぼの調剤',
    location: '愛知県・小牧市',
    photo: 'photos/p05.jpg',
    photoSeed: 'yuya',
    photoHue: 40,
    specialties: ['kampo', 'lifestyle', 'chronic'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '"なんとなく不調"に応えたい。漢方で見つける、あなたの本来の元気。',
    profile: '薬剤師として15年以上の経験を持ち、2018年頃から草漢堂薬局の一員として漢方相談に力を入れています。「検査では異常がないのに、つらい」という声を多く耳にする中で漢方の可能性を実感。慢性的な疲れ・だるさ・睡眠の質の悪さ・原因不明の体調不良など、他の治療法で改善しなかった不調に向き合います。',
    career: [
      '薬剤師として15年以上の経験を積む',
      '2018年頃より草漢堂薬局の一員として漢方相談に本格従事',
    ],
    consultationStyle: '「同じ症状でも原因が違う」という視点で、一人ひとりの背景と体質をじっくり見ながら、話すことを大切に相談を進めます。',
    availableMethods: ['オンライン面談', '店舗相談'],
    tags: ['漢方', '慢性疲労', '不眠', 'なんとなく不調', '生活習慣'],
    yearsOfExperience: 15,
  },
];

const CONSULT_CATEGORIES = [
  { id: 'interact', label: '薬の飲み合わせ', desc: '処方薬・市販薬・サプリの組み合わせの不安' },
  { id: 'side',     label: '副作用',         desc: '出ている症状が薬のせいか整理したい' },
  { id: 'otc',      label: '市販薬',         desc: 'ドラッグストアで何を選べばいいか' },
  { id: 'kampo',    label: '漢方',           desc: '体質や症状に合う漢方薬を相談' },
  { id: 'supp',     label: 'サプリメント',   desc: '本当に必要か、選び方を確認' },
  { id: 'kids',     label: '子どもの薬',     desc: '発熱・解熱剤・飲ませ方の工夫' },
  { id: 'women',    label: '女性の健康',     desc: '生理・更年期・妊娠・授乳期の薬' },
  { id: 'lifestyle',label: '生活習慣',       desc: '食事・睡眠・運動と薬の関係' },
  { id: 'visit',    label: '受診の目安',     desc: '病院に行くべきか、まず整理' },
  { id: 'other',    label: 'その他',         desc: '上記に当てはまらないご相談' },
];

window.HY_DATA = { SPECIALTIES, PHARMACISTS, CONSULT_CATEGORIES };
