// ヒトヤク — 8名の薬剤師ダミーデータ + カテゴリ・タグ定義
// CMS / DB から差し替え可能な形に分離。
// プレースホルダー写真は色相+イニシャルで生成（image-slot で差し替え可能）。

const SPECIALTIES = [
  { id: 'kampo',      label: '漢方',         hue: 140 },
  { id: 'otc',        label: '市販薬',       hue:  30 },
  { id: 'supplement', label: 'サプリメント',  hue:  50 },
  { id: 'women',      label: '女性の健康',    hue: 340 },
  { id: 'pediatric',  label: '子育て・小児',  hue:  20 },
  { id: 'lifestyle',  label: '生活習慣',      hue: 200 },
  { id: 'chronic',    label: '慢性疾患',      hue: 220 },
  { id: 'interact',   label: '飲み合わせ',    hue: 280 },
  { id: 'sideeffect', label: '副作用',        hue:   0 },
  { id: 'language',   label: '外国語対応',    hue: 180 },
];

const PHARMACISTS = [
  {
    id: 'p01',
    name: '中村 結衣',
    nameKana: 'なかむら ゆい',
    title: '薬剤師 / 漢方薬・生薬認定薬剤師',
    pharmacyName: 'みどり薬局 表参道店',
    location: '東京都・港区',
    photoSeed: 'yui',
    photoHue: 140,
    specialties: ['kampo', 'women', 'lifestyle'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online', // online | busy | off
    shortMessage: '冷えや月経まわりのお悩みを、漢方の視点でゆっくり伺います。',
    profile: '大学院で漢方医学を専攻。15年にわたり女性の体調・冷え・不眠などの相談を受けてきました。「症状の奥にある生活」に目を向け、薬だけに頼らない選択肢もご提案します。',
    career: ['2008 京都大学薬学部卒','2010 漢方薬・生薬認定薬剤師取得','2015 大手チェーン薬局にて女性外来担当','2022 みどり薬局へ移籍'],
    consultationStyle: '結論を急がず、生活背景を伺いながら一緒に整理していくスタイルです。',
    availableMethods: ['LINE', 'オンライン面談', '店舗相談', 'メール'],
    tags: ['漢方','女性外来','冷え性','睡眠'],
    yearsOfExperience: 16,
  },
  {
    id: 'p02',
    name: '佐藤 健介',
    nameKana: 'さとう けんすけ',
    title: '薬剤師 / 日本薬剤師研修センター認定実務実習指導薬剤師',
    pharmacyName: 'たんぽぽ薬局 千駄木店',
    location: '東京都・文京区',
    photoSeed: 'kensuke',
    photoHue: 200,
    specialties: ['interact', 'sideeffect', 'chronic'],
    languages: ['日本語', 'English'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '複数の薬を飲んでいる方へ。飲み合わせの不安を、ていねいに整理します。',
    profile: '糖尿病・高血圧など、長くお薬と付き合う方の相談が専門。「処方薬と市販薬・サプリの組み合わせ」の不安を、リスクを過剰に煽らず、しかし曖昧にもせず、わかりやすくお伝えします。',
    career: ['2005 東京理科大学薬学部卒','2011 病院薬剤師として循環器病棟担当','2018 認定実務実習指導薬剤師取得'],
    consultationStyle: 'お薬手帳の写真をお送りいただければ、その場で整理できます。',
    availableMethods: ['LINE', 'オンライン面談', '店舗相談'],
    tags: ['飲み合わせ','慢性疾患','高血圧','糖尿病','英語対応'],
    yearsOfExperience: 21,
  },
  {
    id: 'p03',
    name: '林 桃子',
    nameKana: 'はやし ももこ',
    title: '薬剤師 / 小児薬物療法認定薬剤師',
    pharmacyName: 'こども薬局 自由が丘',
    location: '東京都・目黒区',
    photoSeed: 'momoko',
    photoHue: 20,
    specialties: ['pediatric', 'otc', 'sideeffect'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'busy',
    shortMessage: 'お子さんの薬や発熱、夜中の「これって大丈夫?」をご一緒に。',
    profile: '小児科門前薬局で10年。「子どもに薬を飲ませる工夫」「兄弟で違う薬を飲ませるときの注意」など、日常の困りごとに即した相談を受けています。',
    career: ['2012 共立薬科大学卒','2015 小児科門前薬局勤務','2020 小児薬物療法認定薬剤師取得'],
    consultationStyle: '受診の目安についても、押しつけずにお伝えします。',
    availableMethods: ['LINE', '店舗相談'],
    tags: ['子ども','発熱','解熱剤','市販薬'],
    yearsOfExperience: 13,
  },
  {
    id: 'p04',
    name: '王 海寧',
    nameKana: 'おう かいねい',
    title: '薬剤師 / 在宅療養支援認定薬剤師',
    pharmacyName: 'みどり薬局 新大久保店',
    location: '東京都・新宿区',
    photoSeed: 'haining',
    photoHue: 180,
    specialties: ['language', 'chronic', 'interact'],
    languages: ['日本語', '中文', 'English'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '中国語・英語でのご相談に対応します。ご家族の通訳代わりにも。',
    profile: '日本で薬剤師資格を取得後、外国籍の患者さんへの服薬指導を中心に活動。在宅医療チームの一員として、ご家族・介護者へのサポートも行います。',
    career: ['2014 北京大学薬学部卒','2017 来日、日本の薬剤師資格取得','2021 在宅療養支援認定薬剤師取得'],
    consultationStyle: 'ゆっくり話します。聞き返してくださって大丈夫です。',
    availableMethods: ['LINE', 'オンライン面談', '店舗相談'],
    tags: ['多言語','中文','English','在宅','高齢者'],
    yearsOfExperience: 12,
  },
  {
    id: 'p05',
    name: '渡辺 まり子',
    nameKana: 'わたなべ まりこ',
    title: '薬剤師 / NR・サプリメントアドバイザー',
    pharmacyName: 'たんぽぽ薬局 二子玉川店',
    location: '東京都・世田谷区',
    photoSeed: 'mariko',
    photoHue: 50,
    specialties: ['supplement', 'lifestyle', 'women'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: 'サプリって本当に必要? 商品名に振り回されない選び方を、一緒に。',
    profile: '「サプリは飲んでいいの?」「鉄分は何で摂るのが良い?」など、健康情報があふれる中での迷いをほどく相談を専門としています。',
    career: ['2009 昭和薬科大学卒','2013 NR・サプリメントアドバイザー取得','2019 健康食品管理士'],
    consultationStyle: '販売目的ではなく、必要ないときは「不要です」とお伝えします。',
    availableMethods: ['LINE', 'オンライン面談'],
    tags: ['サプリ','栄養','貧血','疲れ'],
    yearsOfExperience: 17,
  },
  {
    id: 'p06',
    name: '高橋 直人',
    nameKana: 'たかはし なおと',
    title: '薬剤師 / 認定スポーツファーマシスト',
    pharmacyName: 'スター薬局 渋谷店',
    location: '東京都・渋谷区',
    photoSeed: 'naoto',
    photoHue: 220,
    specialties: ['lifestyle', 'otc', 'supplement'],
    languages: ['日本語', 'English'],
    onlineAvailable: true,
    inPersonAvailable: true,
    status: 'online',
    shortMessage: '運動・食事・睡眠と薬の関係。「無理のない継続」をご一緒に考えます。',
    profile: '生活習慣の改善期にある方や、運動を再開する方の相談を多く担当。ドーピング・パフォーマンスへの薬の影響にも詳しいです。',
    career: ['2010 千葉大学薬学部卒','2016 認定スポーツファーマシスト取得'],
    consultationStyle: '数字や根拠を示しながら、押しつけずに選択肢を提示します。',
    availableMethods: ['LINE', 'オンライン面談', '店舗相談'],
    tags: ['生活習慣','スポーツ','英語対応'],
    yearsOfExperience: 16,
  },
  {
    id: 'p07',
    name: '小林 美咲',
    nameKana: 'こばやし みさき',
    title: '薬剤師 / 妊婦・授乳婦薬物療法認定薬剤師',
    pharmacyName: 'みどり薬局 吉祥寺店',
    location: '東京都・武蔵野市',
    photoSeed: 'misaki',
    photoHue: 340,
    specialties: ['women', 'pediatric', 'sideeffect'],
    languages: ['日本語'],
    onlineAvailable: true,
    inPersonAvailable: false,
    status: 'online',
    shortMessage: '妊娠中・授乳中のお薬の不安。気軽に確認できる相手でありたい。',
    profile: '産婦人科病院での経験を活かし、妊娠中・授乳中のお薬や市販薬の選び方を相談。「飲んでしまった、どうしよう」を落ち着いて整理できます。',
    career: ['2011 帝京大学薬学部卒','2017 妊婦・授乳婦薬物療法認定薬剤師取得'],
    consultationStyle: '安心と現実的なリスク、両方を率直にお伝えします。',
    availableMethods: ['LINE', 'オンライン面談'],
    tags: ['妊娠','授乳','女性の健康'],
    yearsOfExperience: 15,
  },
  {
    id: 'p08',
    name: '田口 修一',
    nameKana: 'たぐち しゅういち',
    title: '薬剤師 / かかりつけ薬剤師',
    pharmacyName: 'たんぽぽ薬局 大田区蒲田店',
    location: '東京都・大田区',
    photoSeed: 'shuichi',
    photoHue: 280,
    specialties: ['chronic', 'interact', 'lifestyle'],
    languages: ['日本語'],
    onlineAvailable: false,
    inPersonAvailable: true,
    status: 'off',
    shortMessage: 'ご家族のお薬整理から、生活全体を一緒に。',
    profile: '高齢のご家族の薬を整理したい、複数の病院から処方を受けて不安、そういったご家族からのご相談を多く受けてきました。',
    career: ['1998 北里大学薬学部卒','2002 病院薬剤師','2016 かかりつけ薬剤師認定'],
    consultationStyle: '時間をかけて、ご家族の状況からお話を伺います。',
    availableMethods: ['店舗相談', '電話'],
    tags: ['高齢者','家族の薬','ポリファーマシー'],
    yearsOfExperience: 28,
  },
];

const CONSULT_CATEGORIES = [
  { id: 'interact', label: '薬の飲み合わせ', desc: '処方薬・市販薬・サプリの組み合わせの不安' },
  { id: 'side',     label: '副作用',         desc: '出ている症状が薬のせいか整理したい' },
  { id: 'otc',      label: '市販薬',         desc: 'ドラッグストアで何を選べばいいか' },
  { id: 'kampo',    label: '漢方',           desc: '体質や症状に合う漢方薬を相談' },
  { id: 'supp',     label: 'サプリメント',   desc: '本当に必要か、選び方を確認' },
  { id: 'kids',     label: '子どもの薬',     desc: '発熱・解熱剤・飲ませ方の工夫' },
  { id: 'women',    label: '女性の健康',     desc: '生理・更年期・妊娠・授乳期の薬' },
  { id: 'lifestyle',label: '生活習慣',       desc: '食事・睡眠・運動と薬の関係' },
  { id: 'visit',    label: '受診の目安',     desc: '病院に行くべきか、まず整理' },
  { id: 'other',    label: 'その他',         desc: '上記に当てはまらないご相談' },
];

window.HY_DATA = { SPECIALTIES, PHARMACISTS, CONSULT_CATEGORIES };
